import { Expense } from '../types';

// Generate dynamic dates relative to today
const getDateDaysAgo = (daysAgo: number): string => {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const INITIAL_DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp-101',
    title: 'Whole Foods Organic Groceries',
    amount: 114.50,
    category: 'Groceries',
    date: getDateDaysAgo(0),
    paymentMethod: 'Credit Card',
    notes: 'Fresh veggies, fruits, sourdough bread, almond milk',
    createdAt: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: 'exp-102',
    title: 'Specialty Espresso & Croissant',
    amount: 8.75,
    category: 'Food & Dining',
    date: getDateDaysAgo(0),
    paymentMethod: 'Digital Wallet',
    notes: 'Morning coffee meeting at Artisan Roasters',
    createdAt: Date.now() - 1000 * 60 * 60 * 5,
  },
  {
    id: 'exp-103',
    title: 'Uber City Commute',
    amount: 24.20,
    category: 'Transportation',
    date: getDateDaysAgo(1),
    paymentMethod: 'Credit Card',
    notes: 'Trip to downtown client office',
    createdAt: Date.now() - 1000 * 60 * 60 * 26,
  },
  {
    id: 'exp-104',
    title: 'Fiber Internet Subscription',
    amount: 69.99,
    category: 'Utilities',
    date: getDateDaysAgo(2),
    paymentMethod: 'Bank Transfer',
    notes: 'Monthly 1Gbps high-speed home internet',
    createdAt: Date.now() - 1000 * 60 * 60 * 50,
  },
  {
    id: 'exp-105',
    title: 'Weekend Dinner with Friends',
    amount: 78.40,
    category: 'Food & Dining',
    date: getDateDaysAgo(3),
    paymentMethod: 'Debit Card',
    notes: 'Italian trattoria dinner + dessert',
    createdAt: Date.now() - 1000 * 60 * 60 * 75,
  },
  {
    id: 'exp-106',
    title: 'Monthly Gym & Fitness Membership',
    amount: 45.00,
    category: 'Personal Care',
    date: getDateDaysAgo(5),
    paymentMethod: 'Credit Card',
    notes: 'Equinox pass + locker access',
    createdAt: Date.now() - 1000 * 60 * 60 * 120,
  },
  {
    id: 'exp-107',
    title: 'Apartment Monthly Rent',
    amount: 1250.00,
    category: 'Housing & Rent',
    date: getDateDaysAgo(8),
    paymentMethod: 'Bank Transfer',
    notes: 'Primary residence rent payment for current month',
    createdAt: Date.now() - 1000 * 60 * 60 * 190,
  },
  {
    id: 'exp-108',
    title: 'Electricity & Power Utility',
    amount: 82.35,
    category: 'Utilities',
    date: getDateDaysAgo(9),
    paymentMethod: 'Debit Card',
    notes: 'City power grid monthly bill',
    createdAt: Date.now() - 1000 * 60 * 60 * 215,
  },
  {
    id: 'exp-109',
    title: 'Netflix & Spotify Streaming',
    amount: 28.98,
    category: 'Entertainment',
    date: getDateDaysAgo(11),
    paymentMethod: 'Credit Card',
    notes: 'Family 4K plan and music streaming',
    createdAt: Date.now() - 1000 * 60 * 60 * 260,
  },
  {
    id: 'exp-110',
    title: 'New Running Shoes',
    amount: 135.00,
    category: 'Shopping',
    date: getDateDaysAgo(14),
    paymentMethod: 'Credit Card',
    notes: 'Nike Pegasus road running shoes',
    createdAt: Date.now() - 1000 * 60 * 60 * 330,
  },
  {
    id: 'exp-111',
    title: 'Doctor Visit & Prescription',
    amount: 55.00,
    category: 'Healthcare',
    date: getDateDaysAgo(16),
    paymentMethod: 'Debit Card',
    notes: 'Routine seasonal checkup and vitamins',
    createdAt: Date.now() - 1000 * 60 * 60 * 380,
  },
  {
    id: 'exp-112',
    title: 'Frontend Mastery Book & Course',
    amount: 49.00,
    category: 'Education',
    date: getDateDaysAgo(19),
    paymentMethod: 'Digital Wallet',
    notes: 'React architecture and system design workshop',
    createdAt: Date.now() - 1000 * 60 * 60 * 450,
  },
  {
    id: 'exp-113',
    title: 'Trader Joe\'s Weekly Stockup',
    amount: 86.40,
    category: 'Groceries',
    date: getDateDaysAgo(22),
    paymentMethod: 'Debit Card',
    notes: 'Frozen meals, snacks, dairy, produce',
    createdAt: Date.now() - 1000 * 60 * 60 * 520,
  },
  {
    id: 'exp-114',
    title: 'Gas Station Fuel Fill-up',
    amount: 48.50,
    category: 'Transportation',
    date: getDateDaysAgo(26),
    paymentMethod: 'Credit Card',
    notes: 'Full tank regular unleaded',
    createdAt: Date.now() - 1000 * 60 * 60 * 620,
  },
  {
    id: 'exp-115',
    title: 'Weekend Train Ticket',
    amount: 32.00,
    category: 'Travel',
    date: getDateDaysAgo(32),
    paymentMethod: 'UPI',
    notes: 'Roundtrip express ticket for weekend getaway',
    createdAt: Date.now() - 1000 * 60 * 60 * 760,
  },
  {
    id: 'exp-116',
    title: 'Home Goods & Desk Lamp',
    amount: 64.99,
    category: 'Shopping',
    date: getDateDaysAgo(38),
    paymentMethod: 'Credit Card',
    notes: 'Minimalist warm LED desk lamp',
    createdAt: Date.now() - 1000 * 60 * 60 * 900,
  },
];

export const DEFAULT_BUDGET_CONFIG = {
  monthlyBudget: 2800,
  currencySymbol: '$',
  currencyCode: 'USD',
  categoryBudgets: {
    'Food & Dining': 400,
    'Groceries': 450,
    'Transportation': 200,
    'Housing & Rent': 1300,
    'Utilities': 200,
    'Entertainment': 150,
    'Shopping': 200,
    'Healthcare': 100,
  },
};
